language: node_js
node_js:
  - '0.11'
  - '0.10'
services:
  - mongodb

deploy:
  provider: heroku
  api_key:
    secure: OnVG0UHHaOYYWsLByAU1s77AbTGNaTgHlki3O3YK+oAWwucqDianXOJXmqxAeh5BrtJMMYZmFKwbscKyrKOMtjivhEVcyR+pY5Vcdv22J1t4g+BajHzuuHQbuc7vzs4H7tV+oAr06tvlHfIvmfKSkNhHFpIqc1LS6YbYh4EKAWE=
  app:
    master: quote-webservice
    develop: test-quote-webservice
